import { TDateISOTimeStamp } from "./ISODateString.d.ts";
import { Issue } from "./Issue.d.ts";
import { OmbiUser } from "./User.d.ts";

export interface MovieRequest {
    theMovieDbId: number;
    issueId: number;
    issues?: Issue[];
    subscribed: boolean;
    showSubscribe: boolean;
    is4kRequest: boolean;
    rootPathOverride?: number;
    qualityOverride?: number;
    has4KRequest: boolean;
    approved4K: boolean;
    markedAsApproved4K?: TDateISOTimeStamp;
    requestedDate4k?: TDateISOTimeStamp;
    available4K: boolean;
    markedAsAvailable4K?: TDateISOTimeStamp;
    denied4K?: boolean;
    markedAsDenied4K?: TDateISOTimeStamp;
    deniedReason4K?: string;
    requestCombination: number;
    langCode?: string;
    requestStatus?: string;
    canApprove: boolean;
    watchedByRequestedUser: boolean;
    playedByUsersCount: number;
    imdbId?: string;
    overview?: string;
    posterPath?: string;
    releaseDate?: TDateISOTimeStamp;
    digitalReleaseDate?: TDateISOTimeStamp;
    status?: string;
    background?: string;
    released: boolean;
    digitalRelease: boolean;
    title?: string;
    approved: boolean;
    markedAsApproved?: TDateISOTimeStamp;
    requestedDate: TDateISOTimeStamp;
    available: boolean;
    markedAsAvailable?: TDateISOTimeStamp;
    requestedUserId?: string;
    denied?: boolean;
    markedAsDenied?: TDateISOTimeStamp;
    deniedReason?: string;
    requestType: number;
    requestedByAlias?: string;
    requestedUser?: OmbiUser;
    source: number;
    id: number;
  }